/**
 * Style Dictionary config.
 * Registers custom transforms, formats, and actions, then exports build configs
 * that produce CSS, TS, JSON, iOS, and Android outputs from DTCG token sources.
 *
 * Layers: primitives → light (default) → dark (override)
 * Output:  dist/{css,ts,json,ios,android}/
 */

import fs from 'node:fs'
import path from 'node:path'
import { register } from '@tokens-studio/sd-transforms'
import StyleDictionary from 'style-dictionary'

import {
  BUILD_PATH,
  camelToSnake,
  createConfigs,
  createMobileAssetsConfig,
  createPrimitiveConfig,
  createSemanticDarkConfig,
  createSemanticLightConfig,
  hexToComposeColor,
  hexToXcodeColor,
  transformCamelStripPrimitive,
  transformKebabStripPrimitive,
} from './lib.mjs'

// ─── Register pre-built transforms ────────────

register(StyleDictionary)

// ─── Name transforms ────────────

StyleDictionary.registerTransform({
  name: 'name/kebab-strip-primitive',
  type: 'name',
  transform: transformKebabStripPrimitive,
})

StyleDictionary.registerTransform({
  name: 'name/camel-strip-primitive',
  type: 'name',
  transform: transformCamelStripPrimitive,
})

// ─── CSS custom properties ────────────

StyleDictionary.registerFormat({
  name: 'custom/css-variables',
  format: ({ dictionary, options }) => {
    const selector = options?.selector ?? ':root'
    const lines = dictionary.allTokens.map((t) => `  --${t.name}: ${t.$value ?? t.value};`)
    return [
      `/* Auto-generated — do not edit. Generated: ${new Date().toISOString()} */`,
      `${selector} {`,
      ...lines,
      `}`,
      '',
    ].join('\n')
  },
})

// ─── TypeScript ESM ────────────

StyleDictionary.registerFormat({
  name: 'custom/typescript-esm',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => {
      const val = String(t.$value ?? t.value).replace(/'/g, "\\'")
      return `  /** ${t.path.join('.')}${t.comment ? ` — ${t.comment}` : ''} */\n  '${t.name}': '${val}',`
    })
    return [
      '// Auto-generated by Style Dictionary — do not edit.',
      `// Generated: ${new Date().toISOString()}`,
      '',
      'export const tokens = {',
      ...entries,
      '} as const;',
      '',
      'export type TokenKey   = keyof typeof tokens;',
      'export type TokenValue = (typeof tokens)[TokenKey];',
      '',
    ].join('\n')
  },
})

// ─── Flat JSON ────────────

StyleDictionary.registerFormat({
  name: 'custom/json-flat',
  format: ({ dictionary }) => {
    const obj = Object.fromEntries(dictionary.allTokens.map((t) => [t.name, t.$value ?? t.value]))
    return `${JSON.stringify(obj, null, 2)}\n`
  },
})

// ─── Android Compose colors ────────────

StyleDictionary.registerFormat({
  name: 'android/compose-colors',
  format: ({ dictionary, options }) => {
    const packageName = options?.packageName ?? 'design.tokens.colors'
    const objectName = options?.objectName ?? 'Colors'

    const lines = []
    lines.push(`package ${packageName}`, '', 'import androidx.compose.ui.graphics.Color', '')
    lines.push('/**', ' * Auto-generated by Style Dictionary.', ' * DO NOT EDIT.', ' */')
    lines.push(`object ${objectName} {`)

    for (const token of dictionary.allTokens) {
      const value = token.$value ?? token.value

      if (typeof value !== 'string' || !value.startsWith('#')) {
        console.warn(
          `[android/compose-colors] Skipping "${token.$name ?? token.name}": ` +
            `value "${value}" is not a hex color.`,
        )
        continue
      }

      const desc = (token.$comment ?? token.comment) ? ` — ${token.$comment ?? token.comment}` : ''
      lines.push(
        `    /** ${(token.$path ?? token.path).join('.')}${desc} */`,
        `    val ${token.$name ?? token.name} = Color(${hexToComposeColor(value)})`,
      )
    }

    lines.push('}', '')
    return lines.join('\n')
  },
})

// ─── Android colors.xml ────────────

StyleDictionary.registerFormat({
  name: 'custom/android-colors-xml',
  format: ({ dictionary }) => {
    const entry = (t) => {
      const hex = String(t.$value ?? t.value).toUpperCase()
      return `  <!-- ${t.path.join('.')} -->\n  <color name="${t.path.map(camelToSnake).join('_')}">${hex}</color>`
    }
    return [
      `<?xml version="1.0" encoding="utf-8"?>`,
      `<!-- Auto-generated by Style Dictionary — do not edit. -->`,
      `<!-- Generated: ${new Date().toISOString()} -->`,
      `<resources>`,
      ...dictionary.allTokens.map(entry),
      `</resources>`,
      '',
    ].join('\n')
  },
})

// ─── iOS adaptive colorsets ────────────

StyleDictionary.registerAction({
  name: 'generate_ios_colorsets',
  do: () => {
    const light = JSON.parse(fs.readFileSync(path.join(BUILD_PATH.json, 'light-ios.json'), 'utf8'))
    const dark = JSON.parse(fs.readFileSync(path.join(BUILD_PATH.json, 'dark-ios.json'), 'utf8'))
    const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/
    const iosDir = path.join(BUILD_PATH.ios, 'Color.xcassets')
    fs.mkdirSync(iosDir, { recursive: true })

    const names = new Set([...Object.keys(light), ...Object.keys(dark)])

    for (const name of names) {
      const lv = light[name]
      const dv = dark[name]
      if (!HEX_RE.test(lv) || !HEX_RE.test(dv)) {
        if (lv !== dv) {
          console.warn(
            `[generate_ios_colorsets] Skipping "${name}": missing ${!HEX_RE.test(lv) ? 'light' : 'dark'}-mode hex.`,
          )
        }
        continue
      }

      const dir = path.join(iosDir, `${name}.colorset`)
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(
        path.join(dir, 'Contents.json'),
        JSON.stringify(
          {
            info: { author: 'xcode', version: 1 },
            colors: [
              {
                idiom: 'universal',
                appearances: [{ appearance: 'luminosity', value: 'light' }],
                color: hexToXcodeColor(lv),
              },
              {
                idiom: 'universal',
                appearances: [{ appearance: 'luminosity', value: 'dark' }],
                color: hexToXcodeColor(dv),
              },
            ],
          },
          null,
          2,
        ),
      )
    }

    console.log(`[generate_ios_colorsets] Wrote ${names.size} colorsets.`)
  },
  undo: () => {
    fs.rmSync(path.join(BUILD_PATH.ios, 'Color.xcassets'), {
      recursive: true,
      force: true,
    })
  },
})

// ─── Exports ────────────

export const primitiveConfig = createPrimitiveConfig()
export const semanticLightConfig = createSemanticLightConfig()
export const semanticDarkConfig = createSemanticDarkConfig()
export const mobileAssetsConfig = createMobileAssetsConfig()

export const configs = createConfigs()
