export { default as ContactForm } from './blocks/ContactForm.svelte'
export { contactFormSchema } from './blocks/ContactForm.schema'
export { default as CTA } from './blocks/CTA.svelte'
export { ctaSchema } from './blocks/CTA.schema'
export { default as FAQ } from './blocks/FAQ.svelte'
export { faqSchema } from './blocks/FAQ.schema'
export { default as FeatureGrid } from './blocks/FeatureGrid.svelte'
export { featureGridSchema } from './blocks/FeatureGrid.schema'
export { default as Footer } from './blocks/Footer.svelte'
export { footerSchema } from './blocks/Footer.schema'
export { default as Header } from './blocks/Header.svelte'
export { headerSchema } from './blocks/Header.schema'
export { default as Hero } from './blocks/Hero.svelte'
export { heroSchema } from './blocks/Hero.schema'
export { default as ImageBanner } from './blocks/ImageBanner.svelte'
export { imageBannerSchema } from './blocks/ImageBanner.schema'
export { default as ProductGrid } from './blocks/ProductGrid.svelte'
export { productGridSchema } from './blocks/ProductGrid.schema'
export { default as RichText } from './blocks/RichText.svelte'
export { richTextSchema } from './blocks/RichText.schema'
export { default as Spacer } from './blocks/Spacer.svelte'
export { spacerSchema } from './blocks/Spacer.schema'
export { default as Testimonials } from './blocks/Testimonials.svelte'
export { testimonialsSchema } from './blocks/Testimonials.schema'

export { registerAllBlocks } from './register-all'
export { resolveText, type LocalizedText, type LocaleMap } from './utils'
